### ISSUE TITLE
Armorstand null exception

### ISSUE THREAD

**Issue by mrfloris** [mk7a/ItemSoulBind#19]
**Plugin version**
Get plugin version with /ver ItemSoulBind
**Spigot Version**
Get spigot version with /ver

```
> ver ItemSoulBind
[22:00:03 INFO]: ItemSoulBind version 1.2.0
[22:00:03 INFO]: Bind items for a single player's use only
[22:00:03 INFO]: Website: https://github.com/mk7a/ItemSoulBind
[22:00:03 INFO]: Author: mk7a
> ver
[22:00:04 INFO]: This server is running Paper version git-Paper-387 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[22:00:04 INFO]: Checking version, please wait...
[22:00:05 INFO]: Previous version: git-Paper-386 (MC: 1.16.4)
[22:00:05 INFO]: You are 2 version(s) behind
>
```

**Plugin Configuration**
```
# When player interacts with an item with the register string in its lore, item will be soul bound to them
registerString: "%soulbind%"


# SPECIAL BINDS - items with relevant bind string will only be bound in the specified conditions
# Colour is ignored when checking for string. Case sensitive

# Binds when tool is used: used to break block, sword used to hit entity
bindOnUse: false
bouString: "&9Soul binds on use"
# Binds when armor is equipped through in-hand right click
bindOnEquip: false
boeString: "&9Soul binds on equip"
# Binds when item is picked up
bindOnPickup: false
bopString: "&9Soul binds on pickup"

# Disable soul bind particle+sound effects
disableEffects: false

# Display message in item lore of soul bound item
# Use %username% for player name placeholder
displayLoreMsg: true
loreMsg: "&7 ❖ &8Soul bound to %username% &7 ❖ &r"

# Log player detected with item soul bound to another player in console
consoleLogDetection: true

# Prevents placing soul bound blocks
preventPlacing: false

# Prevents crafting with soul bound items
preventCraft: true

# Prevents enchanting with soul bound items
preventEnchant: true

# Prevents anvil use with soul bound items
preventAnvil: true

# Blocks commands when soul bound item is held in hand
# Only provide the first part of the command, e.g. for "/auction sell" :
blockedCommands:
  - "auction"
  - "sell"
  - "ah"
  - "market"
  - "trash"
  - "anvil"
  - "craft"
  - "dispose"


# =======================
# Messages | use '&' for color codes
msgPrefix: "&3 1MB Soul » &r"
denyMsg: "&9This item is soul bound to another player"
detectedItemMessage: "&cAn item soul bound to another player was removed from your inventory. Event has been logged."
detectedItemBroadcast: "was detected with an item soul bound to another player."
noPermissionGeneric: "&rOopsy, that will not work. Ask staff for help maybe?"
noPermissionBindOthers: "&cOopsy, that will not work. Ask staff for help maybe?"
bindSuccess: "This item is now soul bound to you!"
bindErrorHeldItem: "You must be holding an item in your main hand."
bindErrorAlreadyBound: "This item is already soul bound."
bindErrorNoSuchPlayer: "No such player found online."
unbindErrorNotBound: "Item is not soul bound."
unbindSuccess: "&aSoul bind removed."
inventoryProcessSuccess: "&aProcessed inventory of "
craftDeny: "&cCannot craft with soul bound items."
enchantDeny: "&cCannot enchant soul bound items."
anvilDeny: "&cCannot use anvil on soul bound items."
foundItems: "&7Soul bound items found with another player have been returned to you. Use &b/returnItems &7to get them."
noItems: "You have no items to retrieve."
specialBindDone: "&aSpecial bind applied to item."
cmdBlocked: "&cCannot perform this command on a soul bound item."
# ======================

configVersionDoNotModify: 1.4
```

**Plugins List**
If you are running other plugins, please provide a list.

**To Reproduce**
I don't know if CMI is required, but I use CMI and it has an armorstandeditor. 
Get an armorstand, place it, make sure it's not locked with LWC or something, place the item with soul bind in it and let another player open the armorstand and take the item out. They can use it until they drop or touch it. But there's a console error. It shows nothing ingame btw.

**Expected behavior**
Protection from items being swapped between players like this, a msg saying: You cannot take this item from this armorstand, it is soul bound to another player.

**Screenshots**
If applicable, add screenshots to help explain your problem e.g. console error stacktrace
```
[21:49:15 ERROR]: Could not pass event PlayerArmorStandManipulateEvent to ItemSoulBind v1.2.0
java.lang.NullPointerException: null
        at com.mk7a.soulbind.listeners.ItemProtectionListener.onArmorStandManipulate(ItemProtectionListener.java:168) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor309.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-387]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-387]
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.canInteract(ArmorStandManager.java:1095) ~[?:?]
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.openEditor(ArmorStandManager.java:360) ~[?:?]
        at com.Zrips.CMI.Modules.AStand.ArmorStandListener.lambda$0(ArmorStandListener.java:204) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-387]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1289) ~[patched_1.16.4.jar:git-Paper-387]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-387]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-387]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-387]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Additional context**

**Comment by mk7a** [comment]
@mrfloris 

> let another player **open** the armorstand

Are the players placing+taking the item from the armor stand with the CMI Armor Stand Editor GUI? 
If so please send a jar of CMI to mk7a-mc[ᴀᴛ]protonmail.com for me to reproduce this.

**Comment by Zrips** [comment]
@mk7a 
This might be resolved with next update of CMI, made small mistake by passing throw Null for item stacks and i suspect you dint checked for possible null values as in general it should not be a null value.

**Comment by mk7a** [comment]
>  i suspect you dint checked for possible null values as in general it should not be a null value.

Correct.

**Comment by mrfloris** [comment]
CMI 8.8.0.0 has this fixed, unlocked armorstands still allows other players to take the item out of it. But on my server we auto lock armorstands, so generally wont be a problem for me personally.
